### ISSUE TITLE
flownet2_pytorch resample2d_cuda error 

### ISSUE THREAD

**Issue by yisampi** [NVlabs/few-shot-vid2vid#39]
Has anyone encountered this error?
ImportError: /root/miniconda/envs/py36/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19NonVariableTypeMode10is_enabledEv

my environment:
Docker:nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04-py3.6.10
torch:1.2.0

**Comment by zhhezhhe** [comment]
Same problem.

**Comment by k4rth33k** [comment]
You need to compile the flownet module. I believe it's mentioned in the readme.md

**Comment by zhhezhhe** [comment]
> You need to compile the flownet module. I believe it's mentioned in the readme.md

Thank you for your quick reply! I have run bash install.sh to install flownet successfully. But I still got 
```
ImportError: /ssd3/zhaoruiqi/anaconda3/envs/python3/lib/python3.7/site-packages/resample2d_cuda-0.0.0-py3.7-linux-x86_64.egg/resample2d_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```
I use python3.7, pytorch 1.2.0, torchvision 0.4.0, cuda 10.0, gcc4.9
do you think there is a problem with my setup?

**Comment by k4rth33k** [comment]
If you have installed flownet successfully, I don't think the problem is with the setup. I ran it on almost the same setup but with python 3.6 and pip

**Comment by zhhezhhe** [comment]
> If you have installed flownet successfully, I don't think the problem is with the setup. I ran it on almost the same setup but with python 3.6 and pip

There are no errors when I run bash install.sh for flownet2-pytorch. But when I import resample2d_cuda  an error came out 
```
undefined symbol: _ZN2at19NonVariableTypeMode10is_enabledEv
```
Is it a pytorch-version problem? I used pytorch1.2.0 cuda-10.0/cuda-9.2.

**Comment by zhhezhhe** [comment]
The problem is solved. python3.6 is OK.

**Comment by Hamed-Aghapanah** [comment]
Go to the folder:
vid2vid/models/flownet2_pytorch/networks/resample2d_package/

and run the commands:
python3 setup.py build
and
python3 setup.py install

in that order, fixed it for me.

**Comment by mamunctg** [comment]
> The problem is solved. python3.6 is OK.

I follow all of your configurations but I am getting errors about the apex package. Could you please help?

 ####################ERROR########
class GradScaler(torch.cuda.amp.GradScaler):
AttributeError: module 'torch.cuda' has no attribute 'amp'

########################

**Comment by songyn95** [comment]
@mamunctg  I also encountered this problem. How did you solve it?

**Comment by digvijayad** [comment]
@songyn95  @mamunctg install the [apex](https://github.com/NVIDIA/apex) package.
